### ISSUE TITLE
Clipping problem on Android

### ISSUE THREAD

**Issue by donpark** [donpark/scalable-css-playing-cards#1]
Kevin Marks reports over Twitter:

> [doesn't quite work on the android browser or chrome on android; getting some odd clipping](https://twitter.com/kevinmarks/status/255115405222346754)
> 
> [the numbers are OK, and the face cards, it's the ♣♡♢♠ that come out clipped](https://twitter.com/kevinmarks/status/255116924592197633)
> 
> [oh, you are using the suit characters then. Must be a font metrics issue, so you need Droid and Roboto to check with. Maybe typekit](https://twitter.com/kevinmarks/status/255118534475120640)

**Comment by Matt-Deacalion** [comment]
I have the same problem with Chromium (22.0.1229.79) on Arch Linux.

**Comment by donpark** [comment]
> [I get weird clipping on the right fourth of the various card symbols. Chrome 18 on nexus 7.](http://news.ycombinator.com/item?id=4626012)

**Comment by donpark** [comment]
Bug verified. Definitely a font-metric issue.

![screenshot](http://farm9.staticflickr.com/8036/8067058368_0f96c0bcc6.jpg)

**Comment by donpark** [comment]
Initial diagnosis is that while `font-size` dictates height of current font, width can vary depending on the platform. Looks like Helvetica and Arial has either same or nearly same dimensions so font-size based layout works on Windows, OS X, and iOS. Dimensions of equivalent fonts on Android and, I think, Linux desktops seem to be wider so suite characters get clipped and rotated suite characters don't line up with non-rotated versions.

**Comment by donpark** [comment]
After trying various tweaks, I haven't found a satisfying solution. Suite symbols on Android and Linux fonts being ugly also points to a more general solution. Tentative plan is to make a custom font containing glyphs for the four suite symbols and initially use it only when font-metrics is not as expected (detected by comparing Canvas.measureText result against font height to get font dimension ratio).

**Comment by donpark** [comment]
Fixed using custom font Suit-Regular created using SVG suit symbols from Chris Aguilar's vector files. This font is now used for all browsers and platforms with @font-face support SHA: 66959625d6e6172063b84b06c7ca11ef17a31694

**Comment by Matt-Deacalion** [comment]
Whoa, nicely done! and yeah, they work absolutely fine for me now. :)

**Comment by donpark** [comment]
Glad you like it. I had to create a custom font containing just those 4 suit symbol characters to fix this but I am happy with the result which is that those symbols will look exactly same on all platforms and browsers regardless of which fonts they have installed. :-)
